version: '3.7'

services: 
  # production
  production:
    hostname: golang_example_production
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    environment: 
      SERVING_PORT: "*:8080"
    volumes: 
      - .:/app
    ports: 
      - "8080:8080"
    command: bash -c "go mod download && go build -o /bin/app . && /bin/app"

  # development
  development:
    hostname: golang_example_development
    container_name: golang_example
    depends_on: 
      - postgres
    restart: unless-stopped
    build: 
      context: .
      dockerfile: Dockerfile
      target: dev
    environment: 
      DEBUG: "true"
      SERVING_PORT: "*:8080"
    volumes: 
      - .:/app
    working_dir: /app
    ports:
      - "8080:8080"
    command: bash -c "go mod download && make watch"

  postgres:
    image: postgres:11
    container_name: golang_example_db
    volumes:
      - golang_example:/var/libs/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=developer
      - POSTGRES_DB=golang_example_db
      - POSTGRES_PORT=5432
    ports:
      - 5432:5432
    networks:
      - net

volumes: 
  golang_example:

networks: 
  net:
    driver: bridge