name: coverage

on: 
  push:
    branchs:
      - master

jobs:
  coverage:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: developer
          POSTGRES_DB: golang_example_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.13.x
        id: go

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test preparation
        run: cp .env.example .env

      - name: Calc coverage
        run: |
          go test ./__tests__/ -v -coverpkg=./... -covermode=count -coverprofile=coverage.txt.tmp
          cat coverage.txt.tmp | grep -v "app/application.go" | grep -v "database/" | grep -v "package/" > coverage.txt

      - name: Upload coverage report to CodeCov
        uses: codecov/codecov-action@v1
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage.txt
          fail_ci_if_error: true