name: test

on: 
  push:
    branchs:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: developer
          POSTGRES_DB: golang_example_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.13.x
        id: go

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: go test ./__tests__/ -v -coverpkg=./... -covermode=count
        env:
          POSTGRES_PASSWORD: developer
          POSTGRES_DB: golang_example_db
          POSTGRES_USER: postgres
          POSTGRES_PORT: 5432
          POSTGRES_HOST: postgres

  coverage:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      if: success()
      uses: actions/setup-go@v2
      with:
        go-version: 1.13.x

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Calc coverage 
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin   
        go test ./__tests__/ -v -coverpkg=./... -covermode=count -coverprofile=coverage.out

    - name: Convert coverage to lcov
      uses: jandelgado/gcov2lcov-action@v1.0.0
      with:
          infile: coverage.out
          outfile: coverage.lcov
          
    - name: Coveralls
      uses: coverallsapp/github-action@v1.0.1
      with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: coverage.lcov