name: test

on: 
  push:
    branchs:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: developer
          POSTGRES_DB: golang_example_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.13.x
        id: go

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test preparation
        run: cp .env.example .env

      - name: Run tests
        run: go test ./__tests__/ -v -coverpkg=./... -covermode=count