name: test

on: 
  push:
    branchs:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: developer
          POSTGRES_DB: golang_example_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      zookeeper:
        image: confluentinc/cp-zookeeper:4.1.0
        env: 
          ZOOKEEPER_SERVER_ID: 1
          ZOOKEEPER_CLIENT_PORT: 2181
          ZOOKEEPER_TICK_TIME: 2000
          ZOOKEEPER_INIT_LIMIT: 5
          ZOOKEEPER_SYNC_LIMIT: 3

      kafka:
        image: confluentinc/cp-kafka:4.1.0
        env: 
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
        ports: 
          - 9092:9092
        extra_hosts: 
          kafka: 127.0.0.1
    
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.13.x
        id: go

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test preparation
        run: cp .env.example .env

      - name: Run tests
        run: go test ./__tests__/ -v -coverpkg=./... -covermode=count